export interface PhotoExif {
  camera: string
  lens: string
  iso: number
  aperture: string
  shutterSpeed: string
  focalLength: string
  dateTaken: string
  location?: string
  fileSize: string
  dimensions: string
}

export interface Photo {
  id: string
  src: string
  title: string
  categories: string[]
  photographer: string
  likes: number
  description: string
  filename: string
  width: number
  height: number
  exif: PhotoExif
}

export const mockPhotos: Photo[] = [
  {
    id: "nature-mountain-sunrise",
    src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600",
    title: "Mountain Sunrise",
    categories: ["Nature", "Landscape"],
    photographer: "Alex Johnson",
    likes: 324,
    description:
      "A breathtaking sunrise over the mountain peaks, captured during a hiking expedition in the Swiss Alps. The golden light creates a magical atmosphere.",
    filename: "mountain_sunrise_landscape.jpg",
    width: 800,
    height: 600,
    exif: {
      camera: "Canon EOS R5",
      lens: "24-70mm f/2.8",
      iso: 100,
      aperture: "f/8",
      shutterSpeed: "1/125",
      focalLength: "35mm",
      dateTaken: "2024-03-15",
      location: "Swiss Alps, Switzerland",
      fileSize: "8.2 MB",
      dimensions: "6720 × 4480",
    },
  },
  {
    id: "urban-city-lights",
    src: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&h=900",
    title: "City Lights",
    categories: ["Urban", "Street"],
    photographer: "Sarah Chen",
    likes: 189,
    description:
      "The vibrant nightlife of downtown captured from a rooftop perspective. Neon lights paint the streets in electric colors.",
    filename: "city_lights_urban.jpg",
    width: 600,
    height: 900,
    exif: {
      camera: "Sony A7R IV",
      lens: "85mm f/1.4",
      iso: 1600,
      aperture: "f/2.8",
      shutterSpeed: "1/60",
      focalLength: "85mm",
      dateTaken: "2024-02-28",
      location: "Tokyo, Japan",
      fileSize: "12.5 MB",
      dimensions: "7952 × 5304",
    },
  },
  {
    id: "nature-ocean-waves",
    src: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=900&h=600",
    title: "Ocean Waves",
    categories: ["Nature", "Seascape"],
    photographer: "Mike Rodriguez",
    likes: 456,
    description:
      "Powerful waves crashing against the rocky coastline during golden hour. The raw power of nature captured in perfect timing.",
    filename: "ocean_waves_nature.jpg",
    width: 900,
    height: 600,
    exif: {
      camera: "Nikon D850",
      lens: "16-35mm f/2.8",
      iso: 200,
      aperture: "f/11",
      shutterSpeed: "1/250",
      focalLength: "24mm",
      dateTaken: "2024-01-20",
      location: "Big Sur, California",
      fileSize: "15.3 MB",
      dimensions: "8256 × 5504",
    },
  },
  {
    id: "nature-forest-path",
    src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&h=1000",
    title: "Forest Path",
    categories: ["Nature", "Landscape", "Abstract"],
    photographer: "Emma Wilson",
    likes: 203,
    description:
      "A mysterious path winding through an ancient forest, dappled with morning light filtering through the canopy.",
    filename: "forest_path_nature_abstract.jpg",
    width: 700,
    height: 1000,
    exif: {
      camera: "Fujifilm X-T4",
      lens: "50mm f/1.2",
      iso: 400,
      aperture: "f/4",
      shutterSpeed: "1/125",
      focalLength: "50mm",
      dateTaken: "2024-04-10",
      location: "Black Forest, Germany",
      fileSize: "9.8 MB",
      dimensions: "6240 × 4160",
    },
  },
  {
    id: "urban-street-art",
    src: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=800",
    title: "Street Art",
    categories: ["Urban", "Street", "Abstract"],
    photographer: "David Kim",
    likes: 167,
    description:
      "Colorful street art bringing life to an urban wall in the arts district. A perfect blend of creativity and urban culture.",
    filename: "street_art_urban_abstract.jpg",
    width: 800,
    height: 800,
    exif: {
      camera: "Leica Q2",
      lens: "28mm f/1.7",
      iso: 800,
      aperture: "f/2.8",
      shutterSpeed: "1/60",
      focalLength: "28mm",
      dateTaken: "2024-03-05",
      location: "Berlin, Germany",
      fileSize: "6.7 MB",
      dimensions: "4752 × 3168",
    },
  },
  {
    id: "landscape-desert-dunes",
    src: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1000&h=600",
    title: "Desert Dunes",
    categories: ["Landscape", "Nature"],
    photographer: "Lisa Thompson",
    likes: 378,
    description:
      "Rolling sand dunes creating mesmerizing patterns in the Sahara Desert. The interplay of light and shadow creates natural art.",
    filename: "desert_dunes_landscape.jpg",
    width: 1000,
    height: 600,
    exif: {
      camera: "Canon EOS R6",
      lens: "70-200mm f/2.8",
      iso: 100,
      aperture: "f/8",
      shutterSpeed: "1/250",
      focalLength: "135mm",
      dateTaken: "2024-02-14",
      location: "Sahara Desert, Morocco",
      fileSize: "11.2 MB",
      dimensions: "5472 × 3648",
    },
  },
  {
    id: "automotive-vintage-car",
    src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&h=600",
    title: "Vintage Car",
    categories: ["Automotive", "Street"],
    photographer: "Tom Anderson",
    likes: 292,
    description:
      "A classic 1960s convertible parked on a quiet suburban street. Timeless elegance captured in automotive design.",
    filename: "vintage_car_automotive.jpg",
    width: 900,
    height: 600,
    exif: {
      camera: "Sony A7 III",
      lens: "24-105mm f/4",
      iso: 200,
      aperture: "f/5.6",
      shutterSpeed: "1/125",
      focalLength: "85mm",
      dateTaken: "2024-03-22",
      location: "Los Angeles, California",
      fileSize: "7.9 MB",
      dimensions: "6000 × 4000",
    },
  },
  {
    id: "nature-flower-garden",
    src: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=800",
    title: "Flower Garden",
    categories: ["Nature", "Macro"],
    photographer: "Maria Garcia",
    likes: 434,
    description:
      "A vibrant garden in full bloom with butterflies dancing among the flowers. Nature's palette in perfect harmony.",
    filename: "flower_garden_nature_macro.jpg",
    width: 600,
    height: 800,
    exif: {
      camera: "Olympus OM-D E-M1",
      lens: "60mm f/2.8 Macro",
      iso: 400,
      aperture: "f/4",
      shutterSpeed: "1/250",
      focalLength: "60mm",
      dateTaken: "2024-04-18",
      location: "Keukenhof, Netherlands",
      fileSize: "5.4 MB",
      dimensions: "4608 × 3456",
    },
  },
  {
    id: "urban-architecture",
    src: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&h=1000",
    title: "Modern Architecture",
    categories: ["Urban", "Abstract"],
    photographer: "James Lee",
    likes: 187,
    description:
      "Modern architectural lines creating geometric patterns against the sky. The intersection of art and engineering.",
    filename: "architecture_urban_abstract.jpg",
    width: 700,
    height: 1000,
    exif: {
      camera: "Nikon Z7",
      lens: "14-24mm f/2.8",
      iso: 100,
      aperture: "f/8",
      shutterSpeed: "1/200",
      focalLength: "18mm",
      dateTaken: "2024-01-30",
      location: "Dubai, UAE",
      fileSize: "13.7 MB",
      dimensions: "8256 × 5504",
    },
  },
  {
    id: "nature-wildlife-eagle",
    src: "https://images.unsplash.com/photo-1551522435-a13afa10f103?w=800&h=1000",
    title: "Soaring Eagle",
    categories: ["Nature", "Wildlife"],
    photographer: "Robert Chen",
    likes: 512,
    description: "A majestic eagle soaring through the mountain valleys. The embodiment of freedom and wild beauty.",
    filename: "eagle_wildlife_nature.jpg",
    width: 800,
    height: 1000,
    exif: {
      camera: "Canon EOS-1D X Mark III",
      lens: "100-400mm f/4.5-5.6",
      iso: 800,
      aperture: "f/5.6",
      shutterSpeed: "1/1000",
      focalLength: "400mm",
      dateTaken: "2024-03-08",
      location: "Yellowstone National Park",
      fileSize: "16.8 MB",
      dimensions: "6720 × 4480",
    },
  },
  {
    id: "portrait-street-musician",
    src: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=900",
    title: "Street Musician",
    categories: ["Portrait", "Street"],
    photographer: "Anna Martinez",
    likes: 298,
    description:
      "A talented street musician lost in the rhythm, bringing music to the urban landscape. Art in its purest form.",
    filename: "musician_portrait_street.jpg",
    width: 600,
    height: 900,
    exif: {
      camera: "Sony A7R V",
      lens: "85mm f/1.4",
      iso: 1600,
      aperture: "f/2",
      shutterSpeed: "1/125",
      focalLength: "85mm",
      dateTaken: "2024-02-12",
      location: "Paris, France",
      fileSize: "10.3 MB",
      dimensions: "7952 × 5304",
    },
  },
  {
    id: "landscape-aurora",
    src: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1000&h=600",
    title: "Northern Lights",
    categories: ["Landscape", "Nature", "Abstract"],
    photographer: "Erik Johansson",
    likes: 687,
    description:
      "The mesmerizing dance of the Aurora Borealis painting the night sky in ethereal colors. Nature's most spectacular light show.",
    filename: "aurora_landscape_nature_abstract.jpg",
    width: 1000,
    height: 600,
    exif: {
      camera: "Nikon D850",
      lens: "14-24mm f/2.8",
      iso: 3200,
      aperture: "f/2.8",
      shutterSpeed: "15s",
      focalLength: "14mm",
      dateTaken: "2024-01-05",
      location: "Tromsø, Norway",
      fileSize: "18.9 MB",
      dimensions: "8256 × 5504",
    },
  },
  {
    id: "food-coffee-latte-art",
    src: "https://images.unsplash.com/photo-1517256064527-03b7950f7856?w=700&h=700",
    title: "Coffee Latte Art",
    categories: ["Food", "Still Life"],
    photographer: "Jessica Lee",
    likes: 210,
    description: "A beautifully crafted latte with intricate art, perfect for a morning pick-me-up.",
    filename: "coffee_latte_art.jpg",
    width: 700,
    height: 700,
    exif: {
      camera: "iPhone 13 Pro",
      lens: "26mm f/1.5",
      iso: 200,
      aperture: "f/1.5",
      shutterSpeed: "1/60",
      focalLength: "26mm",
      dateTaken: "2024-05-01",
      location: "London, UK",
      fileSize: "3.1 MB",
      dimensions: "4032 × 3024",
    },
  },
  {
    id: "animals-cat-portrait",
    src: "https://images.unsplash.com/photo-1574144611937-0858069d88c3?w=800&h=1000",
    title: "Curious Cat",
    categories: ["Animals", "Portrait"],
    photographer: "Chris Evans",
    likes: 550,
    description: "A close-up portrait of a curious cat with striking green eyes.",
    filename: "curious_cat_portrait.jpg",
    width: 800,
    height: 1000,
    exif: {
      camera: "Canon EOS 5D Mark IV",
      lens: "100mm f/2.8 Macro",
      iso: 400,
      aperture: "f/2.8",
      shutterSpeed: "1/200",
      focalLength: "100mm",
      dateTaken: "2024-04-25",
      fileSize: "9.5 MB",
      dimensions: "6720 × 4480",
    },
  },
  {
    id: "travel-eiffel-tower",
    src: "https://images.unsplash.com/photo-1502602898669-a38738820219?w=900&h=600",
    title: "Eiffel Tower at Sunset",
    categories: ["Travel", "Urban"],
    photographer: "Sophie Dubois",
    likes: 720,
    description: "The iconic Eiffel Tower bathed in the warm glow of a Parisian sunset.",
    filename: "eiffel_tower_sunset.jpg",
    width: 900,
    height: 600,
    exif: {
      camera: "Nikon Z6 II",
      lens: "24-70mm f/4",
      iso: 100,
      aperture: "f/11",
      shutterSpeed: "1/60",
      focalLength: "50mm",
      dateTaken: "2024-03-10",
      location: "Paris, France",
      fileSize: "11.8 MB",
      dimensions: "6048 × 4024",
    },
  },
]
